account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('connexion', views.connexion, name='connexion'),
    path('deconnexion', views.deconnexion, name='deconnexion'),
    path('new_user', views.account_creation, name='creation'),
    path('account', views.account_page, name='account'),
    ]

bp_project/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

bp_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
    path('products/', include('products.urls', namespace='products')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

products/urls.py
from django.urls import path, include
from . import views

app_name = 'products'

urlpatterns = [
    path('search', views.search, name='search'),
    path('detail/<product_id>', views.detail, name='detail'),
    path('substitute/<product_id>', views.substitute, name='substitute'),
    path('save/<sub_id>', views.save, name='save'),
    path('favorites', views.show_favorites, name='show_favorites')
]

bp_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Pur de Beurre</title>

        {% load static %}

        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.12.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'css/styles.css' %}" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="{% url 'home:home' %}">
                    <img src="{% static 'img/logo_pur_beurre.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
                    Pur Beurre</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <form class="form-inline ml-auto my-2 my-lg-0" action="{% url 'products:search' %}" method="post">
                        {% csrf_token %}
                      <input class="form-control mr-sm-2" name="search_products" type="search" placeholder="Chercher" aria-label="Chercher">
                    </form>
                    <ul class="navbar-nav ml-2 my-2 my-lg-0">
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'account:account' %}">
                            <i class="fas fa-user"></i>
                        </a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'products:show_favorites' %}">
                            <i class="fas fa-carrot"></i>
                        </a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" id="logout" href="{% url 'account:deconnexion' %}">
                            <i class="fas fa-sign-out-alt"></i>
                        </a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'account:connexion' %}">
                           <i class="fas fa-sign-in-alt"></i>
                            </a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        {% block content %}{% endblock %}


        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container">
                <div class="row">
                <div class="small text-muted offset-lg-3 col-lg-2">mentions légales</div>
                <div class="small text-muted offset-lg-3 col-lg-2 ">Contact</div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script type="text/javascript" src="{% static 'js/jquery/jquery.min.js' %}"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->
        <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

bp_project/templates/base_login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Base - Pur Beurre Project</title>

        {% load static %}

        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.12.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'css/styles.css' %}" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="{% url 'home:home' %}">
                    <img src="{% static 'img/logo_pur_beurre.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
                    Pur Beurre</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <form class="form-inline ml-auto my-2 my-lg-0">
                      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    </form>
                    <ul class="navbar-nav ml-2 my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="">
                            <img src="{% static 'img/logo_account.png' %}" width="30" height="30" class="d-inline-block align-top" alt="Mon compte">
                        </a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="">
                            <img src="{% static 'img/logo_carotte.png' %}" width="30" height="30" class="d-inline-block align-top" alt="Mes aliments">
                        </a></li>
                        <li class="nav-item" style="display: none"><a class="nav-link js-scroll-trigger" href="{% url 'account:connexion' %}">
                            <img src="{% static 'img/logo_connexion.png' %}" width="30" height="30" class="d-inline-block align-top" alt="Connexion">
                            </a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'account:deconnexion' %}">
                            <img src="{% static 'img/logo_logout.png' %}" width="30" height="30" class="d-inline-block align-top" alt="Déconnexion">
                        </a></li>
                    </ul>
                </div>
            </div>
        </nav>

        {% block content %}{% endblock %}


        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container">
                <div class="row">
                <div class="small text-muted offset-lg-3 col-lg-2">mentions légales</div>
                <div class="small text-muted offset-lg-3 col-lg-2 ">Contact</div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script type="text/javascript" src="{% static 'js/jquery/jquery.min.js' %}"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->
        <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>