bp_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
    path('products/', include('products.urls', namespace='products')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

products/urls.py
from django.urls import path, include
from . import views

app_name = 'products'

urlpatterns = [
    path('search', views.search, name='search'),
    path('detail/<product_id>', views.detail, name='detail'),
    path('substitute/<product_id>', views.substitute, name='substitute'),
    path('save/<sub_id>', views.save, name='save'),
    path('favorites', views.show_favorites, name='show_favorites')
]

products/models.py
from django.db import models
from django.contrib.auth.models import User


# Create a Category on DB
class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)


# Create a Product on DB
class Product(models.Model):
    product_name = models.CharField(max_length=100)
    nutriscore_grade = models.CharField(max_length=1, null=True)
    store = models.TextField(null=True)
    url_picture = models.URLField()
    url_picture_small = models.URLField(null=True)
    url_product = models.URLField()
    description = models.TextField(null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


# Create a Substitute on DB
class Substitute(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    products = models.ManyToManyField(Product, related_name='substitutes')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

products/views.py
import logging

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from .models import Product, Substitute

logger = logging.getLogger(__name__)


def search(request):
    """
    :param request: User's input
    :return: List of products
    """
    search_products = request.POST.get('search_products').lower()
    products_db = Product.objects.filter(product_name__istartswith=
                                         search_products).values()
    context = {
        'products': products_db,
        'search_products': search_products
    }
    logger.info('New search', exc_info=True, extra={
        # Optionally pass a request and we'll grab any information we can
        'request': request,
    })
    return render(request, 'products/aliments.html', context)


def detail(request, product_id):
    """
    :param request: User choose a product
    :param product_id: id of the product
    :return: List of substitutes
    """
    product_chosen = Product.objects.get(pk=product_id)
    # Get substitutes for the product chosen
    category = product_chosen.category_id
    products = Product.objects.filter(category_id=category).values()
    substitutes = [product for product in products if product['nutriscore_grade'] < product_chosen.nutriscore_grade]
    # Get subs already save by the user
    user_id = request.user.id
    sub = Substitute.objects.filter(user_id=user_id).values('id')
    save_sub = [subs for subs in sub]
    save_sub = [subs['id'] for subs in save_sub]
    # Get nutriscore to display on pictures
    context = {
        'product': product_chosen,
        'substitutes': substitutes,
        'save_sub': save_sub,
    }
    return render(request, 'products/resultats.html', context)


def substitute(request, product_id):
    """
    :param request: Description button
    :param product_id: id of a product
    :return: Description page
    """
    substitute_chosen = Product.objects.get(pk=product_id)
    nutriscore = substitute_chosen.nutriscore_grade
    liste_nut = ['a','b','c','d','e']
    for i, value in enumerate(liste_nut):
        if nutriscore == liste_nut[i]:
            liste_nut[i] = value.upper()
    nut = ' '.join(liste_nut)
    context = {
        'substitute': substitute_chosen,
        'nutriscore': nut,
    }
    return render(request, 'products/informations.html', context)


@login_required
def save(request, sub_id):
    """
    :param request: save button
    :param sub_id: id of the substitute
    :return: Favorite list
    """
    fav = Product.objects.get(pk=sub_id)
    user = request.user.id
    try:
        if Substitute.objects.filter(pk=fav.id):
            print("Cet aliment est déjà dans vos favoris")
        else:
            add_favorite = Substitute(id=fav.id, created_at=timezone.now(),
                                      user_id=user)
            add_favorite.save()
            return show_favorites(request)
    except KeyError as e:
        print(e)


@login_required
def show_favorites(request):
    """
    :param request: Favorite button if user is login
    :return: Favorite page
    """
    user_id = request.user.id
    sub = Substitute.objects.filter(user_id=user_id).values('id')
    get_all_subs = []
    for i in sub:
        get_all_subs.append(i['id'])
    favorites = [favorite for favorite in Product.objects.all().values() if
                 favorite['id'] in get_all_subs]
    context = {
        'favorites': favorites,
    }
    return render(request, 'products/favorites.html', context)

products/templates/products/aliments.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


        <!-- Masthead-->
<header class="masthead" style="min-height: 20rem; height: 30vh;">
    <div class="container h-30">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-uppercase text-white font-weight-bold">Résultat de la recherche : {{ search_products }}</h1>
                <hr class="divider my-4" />
            </div>
        </div>
    </div>
</header>

<section class="page-section p-4" id="aliments">
         {% if products|length_is:"0" %}
        <div class="row">
            <div class="text-center">
             <p class="text-muted"> Dommage, aucun aliment ne correspond à votre recherche </p>
            </div>
        </div>
        {% else %}
        <div class="row text-center m-1 p-1">
            {% for product in products %}
            <div class="col-sm-4 text-center">
                <p>{{ product.product_name }}</p>
                <a href="{% url 'products:detail' product_id=product.id %}">
                <img class="img-responsive" src="{{ product.url_picture_small }}" alt="{{ product.product_name }}">
                </a>
             </div>
            {% endfor %}
        </div>
        {% endif %}
</section>

{% endblock %}

products/templates/products/favorites.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<header class="masthead" style="min-height: 20rem; height: 30vh;">
    <div class="container h-30">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-uppercase text-white font-weight-bold">Mes Favoris</h1>
                <hr class="divider my-4" />
            </div>
        </div>
    </div>
</header>

<section class="page-section p-4" id="favorites">
         {% if favorites|length_is:"0" %}
        <div class="row">
            <div class="text-center">
             <p class="text-muted"> Pour l'instant vous n'avez pas d'aliments dans mes favoris </p>
            </div>
        </div>
        {% else %}
        <div class="row text-center m-1 p-1">
            {% for favorite in favorites %}
            <div class="col-sm-4 text-center">
                <p>{{ favorite.product_name }}</p>
                <a href="{% url 'products:substitute' product_id=favorite.id %}">
                <img class="img-responsive" src="{{ favorite.url_picture_small }}" alt="{{ favorite.product_name }}">
                </a>
             </div>
            {% endfor %}
        </div>
        {% endif %}
</section>

{% endblock %}

products/templates/products/informations.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<header class="masthead" style="background-image: url('{{ substitute.url_picture }}'); background-repeat: no-repeat; background-position: center; min-height: 20rem; height: 30vh;">
    <div class="container h-30">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-uppercase text-grey font-weight-bold">{{ substitute.product_name }}</h1>
                <hr class="divider my-4" />
            </div>
        </div>
    </div>
</header>

<section class="page-section p-4" id="informations">
    <div class="container">
        <div class="row text-center m-1 p-1">
            <div class="col-6 text-center">
                <p> Nutriscore </p>
                <p> {{ nutriscore }}</p>
            </div>
            <div class="col-6 text-center">
                <p> Repères nutritionels <br> pour 100g </p>
             </div>
        </div>
        <div class="row text-center m-1 p-1">
            <div class="col-12 text-center">
            <a class="d-block" href="{{ substitute.url_product }}" style="color:blue;">Voir la fiche d'OpenFoodFacts</a>
            </div>
        </div>
    </div>
</section>

{% endblock %}

products/templates/products/resultats.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Masthead-->
        <header class="masthead" style="background-image: url('{{ product.url_picture }}'); background-repeat: no-repeat; background-position: center; min-height: 20rem; height: 30vh;">
            <div class="container h-30">
                <div class="row h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-10 align-self-end">
                        <h1 class="text-uppercase text-grey font-weight-bold">{{ product.product_name }}</h1>
                        <hr class="divider my-4" />
                    </div>
                </div>
            </div>
        </header>

            <div class="container p-4">
                <h2 class="text-center mt-0">Vous pouvez remplacer cet aliment par : </h2>
                <hr class="divider my-4" />
                {% if substitutes|length_is:"0" %}
                <div class="row">
                    <div class="text-center">
                     <p class="text-muted"> Il n'y a pas d'aliment avec un meilleur nutriscore dans notre base de données </p>
                    </div>
                </div>

                {% else %}
                <div class="row text-center">
                        {% for substitute in substitutes %}
                        <div class="col-sm-4 text-center p-1">

                            <a href="{% url 'products:substitute' product_id=substitute.id %}">
                                <div class="container">
                            <img class="img-responsive" src="{{ substitute.url_picture_small }}" alt="{{ substitute.product_name }}">
                                <div class="top-right">
                                <h3>{{ substitute.nutriscore_grade|upper }}</h3>
                                 </div>
                                </div>
                            </a>

                            <p>{{ substitute.product_name }}</p>
                            {% if user.is_authenticated %}
                                {% if substitute.id in save_sub %}
                                        <p> Sauvegardé </p>
                                    {% else %}
                                    <form class="form-check" action="{% url 'products:save' sub_id=substitute.id %}" method="post">
                                    {% csrf_token %}
                                        <button class="btn btn-outline-secondary" type="submit">
                                            <i class="fas fa-camera"></i>
                                        </button>
                                            Sauvegarder
                                        </form>
                                {% endif %}
                            {% endif %}
                        </div>

                        {% endfor %}
                    </div>
                </div>
                {% endif %}
            </div>



{% endblock %}